# Generated by Django 3.1.6 on 2021-09-16 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=256, verbose_name='آدرس لینک')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='برچسب')),
                ('visits', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدیدها')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('status', models.CharField(choices=[('E', 'فعال'), ('D', 'غیر فعال')], default='E', max_length=1, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'URL',
            },
        ),
    ]
