# Generated by Django 3.1.6 on 2021-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='status',
        ),
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
        migrations.AddField(
            model_name='url',
            name='slug',
            field=models.SlugField(default='aksjlf', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
